### ISSUE TITLE
Async dataset for visNetworkData

### ISSUE THREAD

**Issue by Soolan** [seveves/ng2-vis#12]
Hi seveves,
Thank you for this module. I wonder if you can give me a direction regarding async data.
In the current Network demo, the visNetworkData is initialized inside OnInit().
Imagine we have a bunch of nested promises which at the end they generate the desired network object ( i.e. {nodes: [], edges:[]}  ). What is the best way to feed async data to the network graph. 

When I try something like:
`someAsyncFuncs().then( data => {this.visNetworkData = data})`
It doesn't return any error, but the network graph is blank. 
Can you help me with that please?
Thank you.

**Comment by seveves** [comment]
This is related to an issue I am currently working on (see issue #9). When I'm done with this (maybe at the end of the week) you can use a Vis.DataSet instead of a plain object with nodes and edges and changes will update the graph immediately.
Currently you could use the visNetworkService like this: `someAsyncFuncs().then(data => { this.visNetworkService.setData("idOfYourNetwork", data); })`

**Comment by Soolan** [comment]
Thanks man.
