### ISSUE TITLE
'title' not showing

### ISSUE THREAD

**Issue by joel00** [seveves/ng2-vis#15]
Is there any issue with titles? they do not show on hover.

using "ng2-vis": "0.0.2"

**Comment by seveves** [comment]
I will check this and add it to the demo asap

**Comment by seveves** [comment]
The problem is that VisNode and the interface INode do not have the title property. You can add your own interface like `interface VisExNode extends VisNode { title?: string }` ... when using VisExNode in the DataSet then this should work but I will update the visjs typings and create a new version asap.

**Comment by seveves** [comment]
I've published version [0.0.3](https://www.npmjs.com/package/ng2-vis). Please let me know if this version fixes your problem. On my [demo page](https://seveves.github.io/ng2-vis) you can check the network example. There I've added a title on Node 5 and it's working

**Comment by joel00** [comment]
@seveves thanks for the update....  I tried 0.0.3 and I can see the INode with the new property but can't see titles yet... I'm reviewing my code and let you know.

**Comment by armay** [comment]
By the way, 'group' property is also missing on the INode interface. The suggestion about just extending VisNode does not help in my case because VisNode figures explicitly in VisNodes class which I need to import. It would be nice if someone either adds all the properties needed or rewrites VisNodes as VisNodes\<T extends VisNode\>. At the moment one can use \<VisNode\>{...} to cope with this.

**Comment by seveves** [comment]
Alright ... I'll keep this in mind till I make the next change to the typings-vis project. Maybe at the weekend

**Comment by seveves** [comment]
Next release will contain group and cid properties both having IdType (string|number)

**Comment by seveves** [comment]
@armay [latest version 0.0.5](https://www.npmjs.com/package/ng2-vis) should have group property. Please let me know if this works for you.
